#import "PaintingScanner.h"
#import <React/RCTLog.h>
#import <React/RCTUtils.h>

@implementation PaintingScanner

RCT_EXPORT_MODULE(PaintingScanner)

// This is required for Turbo Modules
+ (BOOL)requiresMainQueueSetup
{
  return NO;
}

// This is required for Turbo Modules - will be generated by codegen
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativePaintingScannerSpecJSI>(params);
}

RCT_EXPORT_METHOD(scanPainting:(NSString *)imageUri
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  // TODO: Implement actual scanning logic
  RCTLogInfo(@"Scanning painting from URI: %@", imageUri);
  
  if (!imageUri || imageUri.length == 0) {
    reject(@"INVALID_URI", @"Image URI cannot be empty", nil);
    return;
  }
  
  // Example implementation
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    NSString *result = [NSString stringWithFormat:@"Scanned painting from: %@", imageUri];
    resolve(result);
  });
}

RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD(getScannerVersion)
{
  return @"1.0.0";
}

RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD(isAvailable)
{
  return @YES;
}

@end

